Klassy-Test/Models/Food.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Klassy_Test.Models
{
    public class Food
    {
        public int Id { get; set; }
        public string Url { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public double Price { get; set; }
        [Required]
        public string Description { get; set; }
        [NotMapped,Required]
        public IFormFile Photo { get; set; }
    }
}

Klassy-Test/ViewModels/Foods/FoodsCreateVM.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Klassy_Test.ViewModels.Foods
{
    [Area("AdminPanel")]
    public class FoodsCreateVM
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public double  Price { get; set; }
    }
}

Klassy-Test/Areas/AdminPanel/Controllers/FoodsController.cs
using Klassy_Test.DAL;
using Klassy_Test.Helpers;
using Klassy_Test.Models;
using Klassy_Test.ViewModels.Foods;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Klassy_Test.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class FoodsController : Controller
    {
        private AppDbContext _context{ get; set; }
        private IWebHostEnvironment _env { get; }
        public IEnumerable<Food> Foods { get; set; }
        public FoodsController(AppDbContext context,IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
            Foods = _context.Foods;
        }
        public IActionResult Index()
        {
            return View(_context.Foods.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Food food)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (!food.Photo.CheckFileSize(200))
            {
                ModelState.AddModelError("Photo", "Photo Size Must Be Less Than 200");
            }
            if (!food.Photo.CheckFileType("image/"))
            {
                ModelState.AddModelError("Photo", "File Type Must Be Image");
            }
            
            Food newFood = new Food
            {
                Name = food.Name,
                Description = food.Description,
                Price = food.Price,
                
            };
            newFood.Url = await food.Photo.SaveFileAsync(Path.Combine(_env.WebRootPath, "images"));
           await _context.Foods.AddAsync(newFood);
           await _context.SaveChangesAsync();
           return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var food = _context.Foods.Find(id);
            if (food==null)
            {
                return NotFound();
            }
            var path = Helper.GetPath(_env.WebRootPath, "images", food.Url);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            _context.Foods.Remove(food);
             await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Update(int? id)
        {
            if (id==null)
            {
                return BadRequest();
            }
            Food food = _context.Foods.FirstOrDefault(f=>f.Id==id);
            if (food==null)
            {
                return NotFound();
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, FoodsCreateVM food)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Food foodDb = _context.Foods.FirstOrDefault(f => f.Id == id);
            if (food == null)
            {
                return NotFound();
            }
            if (food.Name.ToLower()==foodDb.Name.ToLower()|| food.Description.ToLower() == foodDb.Description.ToLower()|| food.Price == foodDb.Price)
            {
                return RedirectToAction(nameof(Index));
            }
            bool IsExist = Foods.Any(f => f.Name.ToLower() == food.Name.ToLower() );
            if (IsExist)
            {
                ModelState.AddModelError("Name", $"{food.Name} already exists");
                return View();
            }
            foodDb.Name = food.Name;
            foodDb.Description = food.Description;
            foodDb.Price = food.Price;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Klassy-Test/Areas/AdminPanel/Views/Foods/Create.cshtml
@model Klassy_Test.Models.Food
    @{
        ViewData["Title"] = "Create";
    }
<div class="col-xxl">
    <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5 class="mb-0">Foods</h5>
        </div>
        <div class="card-body">
            <form asp-controller="Foods" asp-action="Create" method="post" enctype="multipart/form-data">
                <div class="row mb-3">
                    <label asp-for="Name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                        <input asp-for="Name" class="form-control" placeholder="Name" />
                        <span asp-validation-for="Name"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Description" class="col-sm-2 col-form-label">Description</label>
                    <div class="col-sm-10">
                        <input asp-for="Description"
                               class="form-control"
                               placeholder="Description">
                        <span asp-validation-for="Description"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Price" class="col-sm-2 col-form-label">Price</label>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <input asp-for="Price"
                                   class="form-control"
                                   placeholder="price" />
                            <span asp-validation-for="Price"></span>
                        </div>
                        <div class="form-text">You can use letters, numbers & periods</div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Photo" class="col-sm-2 col-form-label">Photo</label>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <input asp-for="Photo"
                                   class="form-control"
                                   placeholder="upload photo" />
                            <span asp-validation-for="Photo"></span>
                        </div>
                        <div class="form-text">You can use letters, numbers & periods</div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Create</button>
                <a class="btn btn-primary" asp-action="Index">
                    Cancel
                </a>
            </form>
        </div>
    </div>
</div>

Klassy-Test/Areas/AdminPanel/Views/Foods/Index.cshtml
@model IEnumerable<Food>
@{
    ViewData["Title"] = "Index";
    int count = 1;
}

<div class="card">
    <h5 class="card-header">Foods</h5>
    
    <div class="table-responsive text-nowrap">
        <a asp-action="Create" class="btn btn-success" style="float:right;color:white;margin-right:70px">Create New One</a>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Settings</th>
                </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                @foreach (var food in Model)
                {
                    <tr>
                        <td>@count</td>
                        <td><img style="width:100px;height:100px" src="~/images/@food.Url" class="rounded-circle" /></td>
                        <td>
                            @food.Name
                    </td>
                    <td>@food.Description</td>
                    <td>
                        $@food.Price
                    </td>
                    <td>
                        <a asp-route-id="@food.Id" asp-controller="Foods" asp-action="Update" class="btn btn-warning">Edit</a>
                        <a asp-route-Id="@food.Id" asp-controller="Foods" asp-action="Delete" class="btn btn-danger">
                            Delete
                        </a>
                    </td>
                </tr>
                count++;
            }
            </tbody>
        </table>
    </div>
</div>
<!--/ Bootstrap Dark Table -->

Klassy-Test/Areas/AdminPanel/Views/Foods/Update.cshtml
@model Klassy_Test.ViewModels.Foods.FoodsCreateVM
    @{
        ViewData["Title"] = "Update";
    }
<div class="col-xxl">
    <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between">
            <h5 class="mb-0">Update Foods</h5>
        </div>
        <div class="card-body">
            <form asp-controller="Foods" asp-action="Update" method="post" enctype="multipart/form-data">
                <div class="row mb-3">
                    <label asp-for="Name" class="col-sm-2 col-form-label">Food Name</label>
                    <div class="col-sm-10">
                        <input asp-for="Name" class="form-control" placeholder="Name" />
                        <span asp-validation-for="Name"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Description" class="col-sm-2 col-form-label">Description</label>
                    <div class="col-sm-10">
                        <input asp-for="Description"
                               class="form-control"
                               placeholder="Description">
                        <span asp-validation-for="Description"></span>
                    </div>
                </div>
                <div class="row mb-3">
                    <label asp-for="Price" class="col-sm-2 col-form-label">Price</label>
                    <div class="col-sm-10">
                        <div class="col-sm-10">
                            <input asp-for="Price"
                                   class="form-control"
                                   placeholder="Price" />
                            <span asp-validation-for="Price"></span>
                        </div>
                        <div class="form-text">You can use letters, numbers & periods</div>
                    </div>
                </div>
                <button type="submit" class="btn btn-warning">Save</button>
                <a class="btn btn-primary" asp-action="Index">
                    Cancel
                </a>
            </form>
        </div>
    </div>
</div>